// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace BoardgameDatabase
{
    public partial class BoardgameDBContext : DbContext
    {
        public BoardgameDBContext()
        {
        }

        public BoardgameDBContext(DbContextOptions<BoardgameDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Adress> Adresses { get; set; }
        public virtual DbSet<Boardgame> Boardgames { get; set; }

        //protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        //{
        //    if (!optionsBuilder.IsConfigured)
        //    {
        //        optionsBuilder.UseSqlServer("");
        //    }
        //}

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<Adress>(entity =>
            {
                entity.HasKey(e => e.Name)
                    .HasName("PK__Adresses__737584F7788FE335");
            });

            modelBuilder.Entity<Boardgame>(entity =>
            {
                entity.HasOne(d => d.KeeperNavigation)
                    .WithMany(p => p.BoardgameKeeperNavigations)
                    .HasForeignKey(d => d.Keeper)
                    .HasConstraintName("FK_BG_Keeper");

                entity.HasOne(d => d.OwnerNavigation)
                    .WithMany(p => p.BoardgameOwnerNavigations)
                    .HasForeignKey(d => d.Owner)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_BG_Owner");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}